knp_paginator:
    page_range: 3
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
        page_out_of_range: ignore
        default_limit: 6
    template:
        pagination: 'pagination/custom_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' 